version: '3.8'

services:
  backend:
    image: backend-image
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - APP_ENV=development
