version: '3.8'
services:
  prepare:
    image: alpine
    volumes:
      - ./data/certbot:/data/certbot
    command:
      - sh
      - -c
      - |
        mkdir -p /data/certbot/conf /data/certbot/www
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 168h & wait $${!}; done;'"
    command: "certonly --webroot --webroot-path=/var/www/certbot --email d_maximyuk@icloud.com --agree-tos --no-eff-email --domains dev.e-frontend.ru"
