version: '3.8'
services:
  backend:
    networks:
      - backend-net
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

networks:
  backend-net:
    driver: bridge
